function [ M_isotope, P_totalThermal, P_dissipatedThermal ] = RTGSizing_theoretical( P_electric_required_watt, t_years, conversion_efficiency, fuel_data )

%% PROTOTYPE
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Function computes hypothetical electric power generated by a nuclear fuel
% at time t[years].
%   --> Function is used to compare the best alternatives that can be used as
%       nuclear fuel. From this function, you can decide whether to use a
%       Plutonium-based or Americium-based RTG.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% in1 [dim] description
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% out1 [dim] description
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% Date, User, brief summary of the modification
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% -------------------------------------------------------------------------------------------------------------
%% Future upgrades

%% Function code

% Unpack struct
t_halflife = fuel_data.halflife ; % [years]
specificPower = fuel_data.specificPower ; % [W\kg]
eta_conversion = fuel_data. ; % [percent]

% Compute specific power [W/kg] that isotope can generate at time t
P_specific = @(t_years) specificPower * 2^(-t_years/t_halflife) ; % [W/kg]

% Compute fuel mass required to obtain that electric power
M_isotope = P_electric_required_watt / ( P_specific(t_years) * conversion_efficiency ) ; % [kg]

% Compute overall thermal power that is generated, P_thermal_tot = P_electric + P_dissipated_thermal
P_totalThermal = P_specific(t_years) * M_isotope ;

% Compute the thermal power dissipated to obtain that electric power (useful for TCS evaluation)
P_dissipatedThermal = P_totalThermal * ( 1 - conversion_efficiency ) ;

end