%% Set Latex font
set(groot,'defaulttextinterpreter','latex')
set(groot,'defaultLegendInterpreter','latex')
set(groot,'defaultAxesTickLabelInterpreter','latex')
%%
clearvars; clc; close all

% Solar Flux
AU_earth = 1; 
AU_enc = 9.5;
q_sun_enc = 1367.5/AU_enc^2;
q_sun_earth = 1367.5;

% Albedo 
a_earth = 0.35;
a_enc = 0.8;
a_sat = 0.499;

% View Factors 
R_earth = 6371;
R_orbit_earth = 670 + R_earth;
R_enc = 252.1;
R_orbit_enc_min = 20 + R_enc;
R_orbit_enc_max = 20 + R_enc;
R_sat = 58232;
R_orbit_sat = 238000;
F_earth = (R_earth/R_orbit_earth)^2;
F_enc_max = (R_enc/R_orbit_enc_min)^2;
F_enc_min = (R_enc/R_orbit_enc_max)^2;
F_sat = (R_sat/R_orbit_sat)^2;

% Radiative parameters
sigma_SB = 5.67e-8;
epsilon_Earth = 0.85;
epsilon_Enc = 1;
epsilon_sat = 1;
T_earth = 255.25;
T_Enc = 72;
T_Sat = 97;

%%% Spacecraft %%%

% Area
L1 = 4;
L2 = 4;
L3 = 2;
A1 = L1*L2;
A6 = A1;
A2 = L1*L3;
A4 = A2;
A3 = L2*L3;
A5 = A3;
D_ant = 3.2; % diameter of antenna ??
A_ant = pi*(D_ant/2)^2; 

%%% Structure properties (Al-5056-O)
k_str = 117;
l_str = 0.02;

% Structure
epsilon_int = 0.23; %%%%%%%%%%????????????????' aluminum ???????? -> to change, sentitivity analysis
epsilon_1 = 0.9; %%%%??????????? epsilon of internal node

% MLI 
epsilon_MLI = 0.03;
alpha_MLI = 0.14; % max. typ = 0.12 

% Antenna painted white
epsilon_ant = 0.90;
alpha_ant = 0.18; % do sensitivity analysis

% Thermal stripes
k_TS = 398; 
L_TS = 120e-3; %?????

% Radiators
% changed from 0.8: if louvers open ~0.7
eps_louv_closed = 0.14;
eps_louv_open = 0.7;
eps_rad = eps_louv_closed; % if closed louvers
% eps_rad = 0.8;  % if ideal radiators and not louvers
alpha_louv_closed = 0.062; 
alpha_louv_open = 0.269; % (worst case EOL)
A_rad = 1 * 0.2;
n_rad = 5; %% to change
k_rad = 1;

% RHU or heaters
n_RHU = 50; 
P_RHU = 1; % 1 W is the thermal power generated by each RHU 

% Power
P_budget_hot = 349;
P_input_TMTC_h = 20;
P_diss_TMTC_h = 16.44;
% add batteries ...
We = 676;
Wt = 4506;
Q_hot = P_budget_hot-P_input_TMTC_h+P_diss_TMTC_h;

% view factor
% Surface 1
F12 = VF_PerpRec(L3,L2,L1);
F21 = VF_PerpRec(L2,L3,L1);
F13 = VF_PerpRec(L3,L1,L3);
F31 = F13*A1/A3;
F14 = F12;
F41 = F21;
F15 = F13;
F51 = F31;
F16 = VF_ParallelEqualRec(L3,L1,L2);
F61 = F16;

% Surface 2
F23 = VF_PerpRec(L2,L3,L1);
F32 = F23*A2/A3;
F24 = VF_ParallelEqualRec(L2,L1,L3);
F42 = F24;
F25 = F23;
F52 =F32;
F26 = VF_PerpRec(L2,L3,L1);
F62 = F26*A2/A6;

% Surface 3
F34 = F32;
F43 = F23;
F35 = VF_ParallelEqualRec(L1,L2,L3);
F53 = F35;
F36 = F31;
F63 = F13;

% Surface 4
F45 = F43;
F54 = F34;
F46 = F41; 
F64 = F14;

% Surface 5
F56 = F36; 
F65 = F63;

% Conduction between surfaces


