%% Set Latex font
set(groot,'defaulttextinterpreter','latex')
set(groot,'defaultLegendInterpreter','latex')
set(groot,'defaultAxesTickLabelInterpreter','latex')
%%
clearvars; clc; close all
%%%%%%%%%%%%%%%%%%%%%%%%%%%% DATA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% Environment %%%

% Solar Flux
AU_earth = 1; 
AU_enc = 9.5;
q_sun_enc = 1367.5/AU_enc^2;
q_sun_earth = 1367.5;

% Albedo 
a_earth = 0.35;
a_enc = 0.8;
a_sat = 0.499;

% View Factors 
R_earth = 6371;
R_orbit_earth = 470 + R_earth;
R_enc = 252.1;
R_orbit_enc_min = 20 + R_enc;
R_orbit_enc_max = 20 + R_enc;
R_sat = 58232;
R_orbit_sat = 238000;
F_earth = (R_earth/R_orbit_earth)^2;
F_enc_max = (R_enc/R_orbit_enc_min)^2;
F_enc_min = (R_enc/R_orbit_enc_max)^2;
F_sat = (R_sat/R_orbit_sat)^2;

% Radiative parameters
sigma_SB = 5.67e-8;
epsilon_Earth = 0.85;
epsilon_Enc = 1;
epsilon_sat = 1;
T_earth = 255.25;
T_Enc = 72;
T_Sat = 97;

%%% Spacecraft %%%

%%% Structure properties (Al-5056-O)
k_str = 117;
l_str = 0.02;

% Structure
epsilon_int = 0.23; %%%%%%%%%%????????????????' aluminum ????????
epsilon_ext = 0.62; % aluminized kapton see book
alpha_ext = 0.44; % aluminized kapton
epsilon_1 = 1; %%%%??????????? epsilon of internal node

% MLI 
epsilon_MLI = 0.03;
alpha_MLI = 0.0029;

% Radiators
eps_rad = 0.7; % changed from 0.8: if louvers open ~0.7
eps_louv_closed = 0.14;
% eps_rad = eps_louv_closed; % if closed louvers
% eps_rad = 0.8;  % if ideal radiators and not louvers
alpha_louv_closed = 0.062; 
alpha_louv_open = 0.269; % (worst case EOL)
A_rad = 1*0.2;
n_rad = 2;
k_rad = 1;

% RHU
n_RHU = 50;
P_RHU = 1; % 1 W is the thermal power generated by each RHU 


%%%%%%%%%%%%%% 1. COLD CASE LANDER: ENCELADUS SURFACE %%%%%%%%%%%%%%%%%%%%%

% Power to dissipate internally
P_hot_land = 513 + 20.1; % Electrical power + P dissipated by batteries
P_cold_land = 389;

% Thermal power RTG to radiate to DS / heat S/C: 
P_RTG = 5191;

% Areas
L = 2;
A_1 = n_rad*A_rad;
A_2 = L^2;
A_3 = L^2;
A_4 = (4*L^2 - n_rad*A_rad); 

% Internal View actors
F_23 = 1/5; F_32 = 1/5; F_43 = 1/5; F_42 = 1/5;  
F_24 = 4/5; F_34 = 4/5;

%%%%%%%%% CONDUCTIVE COUPLING (C) AND RADIATIVE COUPLING (R) %%%%%%%%%%%%%%
% LEGEND:
% R_ij means the radiative coupling between nodes i and j
% C_ij means the conductive coupling between nodes i and j

%%% Bottom Surface (2)

R.R_20 = A_2*epsilon_ext; 
R.R_21 = A_2*epsilon_MLI*epsilon_1; 

% C_LB = 4 * k_str*(l_str*L/(L/2) + l_str*L/(L/2));
% R.R_LB = A_L*F_LB*epsilon_int^2;
% R.R_TB = A_T*F_TB*epsilon_int^2;

%%% Top Surface (3)

R.R_31 = A_3 * epsilon_MLI*epsilon_1;
R.R_30 = A_3 * epsilon_ext;

% R.R_BT = A_B*F_BT*epsilon_int^2;
% C_LT = 4 * k_str*(l_str*L/(L/2) + l_str*L/(L/2));
% R.R_LT = A_L*F_LT*epsilon_int^2;

%%% Lateral Surfaces with MLI (4)

% R.R_BL = A_B*F_BL*epsilon_int^2 ;
% R.R_TL = A_T*F_TL*epsilon_int^2 ;

R.R_41 = A_4 * epsilon_MLI*epsilon_1;
R.R_40 = A_4 * epsilon_ext;

%%% Radiator
% (since the radiators exchange heat directly with outside they're like 
% a direct link between 1 and T0 = 0 K)

R.R_10 = A_1 * eps_rad;
% R.R_10 = 1/(1/(A_1*eps_rad)+1/(A_1*epsilon_1*eps_rad)); % ???????????

%%% Heat Flows

% Heat fluxes for Saturn and Enceladus
q_Sat = F_sat*sigma_SB*T_Sat^4*epsilon_sat;
q_Enc = 1 * sigma_SB *T_Enc^4 *epsilon_Enc;

% angles between the normal to the surface and the incident radiation
theta_4Enc = 0;
theta_3Sat = pi/4;
theta_2Sat = pi/4;

% Overall external heat to each node (dissipation is not included)
Q_ext = [q_Sat * A_1*eps_rad*cos(theta_4Enc) ; % or q_Sat * A_1*eps_rad*(A_1*epsilon_1*eps_rad)/(A_1*epsilon_1*eps_rad+A_1*eps_rad)
        q_Enc * A_2*epsilon_ext*cos(theta_2Sat);
        q_Sat * A_3*epsilon_ext*cos(theta_3Sat);
        q_Sat * A_4*epsilon_ext*cos(theta_4Enc)];

%%% Internal dissipation power
Q_diss =  P_cold_land;

%%% SOLVE THE SYSTEM 
T_guess = 273*ones(4,1);
options = optimoptions('fsolve','display','iter','MaxFunctionEvaluations',50000,'Maxiterations',50000);

% Cold case
T_land_cold = fsolve(@(T) HeatBalance_Lander_new(T, R, Q_ext , Q_diss, sigma_SB),T_guess, options);

fprintf(['\nExternal Bottom: ',num2str(T_land_cold(2)-273),' Celsius'])
fprintf(['\nExternal Top: ',num2str(T_land_cold(3)-273),' Celsius'])
fprintf(['\nExternal Lateral: ',num2str(T_land_cold(4)-273),' Celsius\n'])
fprintf(['\nInternal T: ',num2str(T_land_cold(1)-273),' Celsius\n'])

